

line-length = 120
indent-width = 4

[lint]
select = [
    # mccabe (C90), commas (COM), comprehensions (C4)
    "C", 
    # pycodestyle
    "E",
    # Pyflakes
    "F", 
    # isort
    "I",
    # pylint
    "PL", 
    # pycodestyle warnings
    "W"
    ]

# Ignore import violations in all `__init__.py` files.
[lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403", "F811"]

[lint.isort]
lines-after-imports = 2

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"