name: tiny-eps
type: ddit
hidden_size: 128
cond_dim: 32  
length: 64 # tiny sequences 
n_blocks: 4
n_heads: 2
scale_by_sigma: True
dropout: 0.1
tie_word_embeddings: False
# Epsilon-rate conditional implementation of MDLM
conditional: True
cond_method: "proba" # probability-based conditioning
proba_method: "bucket" # bucket + embed 
bias_scale: 0.0