name: medium
type: ddit
hidden_size: 1024
cond_dim: 128
length: 1024
n_blocks: 24
n_heads: 16
scale_by_sigma: True
dropout: 0.1
tie_word_embeddings: False
# Class conditional implementation of MDLM
label_dropout: 0.25 # increased for better guidance
num_classes: 2 # tied to the Amazon polarity dataset (fancyzhx/amazon_polarity)
conditional: True
cond_method: "label" # label-based conditioning